### ISSUE TITLE
[Script Submission]: Import Keyvault secrets via excel sheet

### ISSUE THREAD

**Issue by PieterVandendriessche** [dlw-digitalworkplace/dw-script-lib#15]
### Contact Details

pieter.vandendriessche@delaware.pro

### Description

We have a script available where you can import KeyVault secrets based on an excel file.

### Type

PowerShell

### Add some tags (keywords) to help others find your script (separate by comma)

Azure,Excel

**Comment by agtenr** [comment]
Thanks Pieter. This could indeed be a nice addition to the library. Do you have some time to make a PR for this? If not, you can send the PS1 with an example excel sheet to me and I'll make sure it gets added. 

Thanks for submitting ♥
