### ISSUE TITLE
[Script Submission]: Copy-FolderToDifferentSiteDifferentTenant

### ISSUE THREAD

**Issue by PieterVandendriessche** [dlw-digitalworkplace/dw-script-lib#22]
### Contact Details

pieter.vandendriessche@delaware.pro

### Description

A script to move folder content from one site to another with ShareGate.

### Type

PowerShell

### Add some tags (keywords) to help others find your script (separate by comma)

ShareGate,SharePoint

**Comment by agtenr** [comment]
@PieterVandendriessche Sorry for the delay. Thanks for contributing. Script is available
https://dlw-digitalworkplace.github.io/dw-script-lib/PowerShell/Copy-FolderToDifferentSiteDifferentTenant/Copy-FolderToDifferentSiteDifferentTenant.html

**Comment by agtenr** [comment]
Fixed by #23
