### ISSUE TITLE
[Script Submission]: Reset user's OneDrive storage quota to the tenant wide quota

### ISSUE THREAD

**Issue by PieterVandendriessche** [dlw-digitalworkplace/dw-script-lib#24]
### Description

This script allows a tenant administrator to reset the user's OneDrive storage quota to the tenant's wide setting. When an admin has changed this quota it will not apply to existing users, only new users. With the script this setting is pushed for all users within the tenant.

### Type

PowerShell

### Add some tags (keywords) to help others find your script (separate by comma)

SharePoint, OneDrive, Management, Storage

**Comment by agtenr** [comment]
Thanks @PieterVandendriessche I merged the pr (#25).
